### ISSUE TITLE
Redirection issue on ios 11 and above for other web based AMOP methods

### ISSUE THREAD

**Issue by nevin** [AmadeusITGroup/Checkout-Experience-iOS#1]
https://github.com/AmadeusITGroup/Checkout-Experience-iOS/blob/b2ea78d7c2bc737bb318846a801f5cfb50a82e5b/AmadeusCheckoutCore/AmadeusCheckout/WebRedirectionViewController.swift#L108

The workaround is for ios 10 and below right ? why is it enabled for ios 11 and above? because of this code, the WebView won't send the necessary headers to load the external payment URLs and will fail to load the URL

![image](https://user-images.githubusercontent.com/200027/141400766-51487dbb-161d-4ae7-84f2-00f4e6bfbeeb.png)

**Comment by yann-armelin-1a** [comment]
Indeed the workaround should be enabled  only for iOS 10 and below: there is something wrong with that guard.

We are investigating.

**Comment by yann-armelin-1a** [comment]
Fixed in version 1.0.9
