### ISSUE TITLE
AMPaymentMethod' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by nevin** [AmadeusITGroup/Checkout-Experience-iOS#2]
https://github.com/AmadeusITGroup/Checkout-Experience-iOS/blob/b2ea78d7c2bc737bb318846a801f5cfb50a82e5b/AmadeusCheckoutCore/AmadeusCheckout/AMPaymentMethod.swift#L13

unable to access the init method due to internal protection level

**Comment by yann-armelin-1a** [comment]
This constructor is not meant to be called directly.
Instead you should use instances that are returned by `fetchPaymentMethods`
